name: Run Azure CLI login with OpenID Connect
on: [push]

permissions:
  id-token: write
  contents: read

env:
  AZURE_WEBAPP_NAME: app-explorer-dev-westeu-001
  AZURE_WEBAPP_PACKAGE_PATH: 'resources/app/src'


jobs:
  deploy-webapp: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure CLI Login
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - name: Install dependencies
        run: |
          cd ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Deploy WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

      - name: logout
        run: |
          az logout
